name: build-artifact
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
permissions: read-all    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package assembly:single --file pom.xml
    - name: Release the artifact
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Built from commit ${{ github.sha }}"
        files: |
          target/HTTPSignatures-jar-with-dependencies.jar
