name: build-artifact
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
permissions: read-all    
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package assembly:single --file pom.xml
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ExtensionJarFile
        retention-days: 90
        if-no-files-found: error
        include-hidden-files: false
        path: target/HTTPSignatures-jar-with-dependencies.jar     
